#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# setup-worktree.sh <branch|slug> [base-branch]
#
# Creates an isolated sibling git worktree + branch for one feature, allocates
# a unique port block, and writes the worktree's .env.local.
#
# Worktree path:  ../<primary-basename>-wt-<slug>
#   e.g. /home/felipe/workfolder/imoveis-wt-add-login
#
# Prefer scripts/agent/setup-workspace.sh — it chooses solo branch vs worktree.
#
# Prints the worktree path on the LAST line (machine-readable).
# ---------------------------------------------------------------------------
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$HERE/lib.sh"

[ $# -ge 1 ] || die "usage: setup-worktree.sh <branch|slug> [base-branch]"

INPUT="$1"
if echo "$INPUT" | grep -q '/'; then
  BRANCH="$INPUT"
  validate_conventional_branch "$BRANCH" || die "branch '$BRANCH' violates Conventional Branch v1.1.0"
else
  SLUG="$(sanitize_proj "$INPUT")"
  [ -n "$SLUG" ] || die "empty/invalid feature slug"
  DETECTED_TYPE=""
  while IFS='|' read -ra _types; do
    for _t in "${_types[@]}"; do
      if [[ "$SLUG" == "$_t-"* ]]; then
        DETECTED_TYPE="$_t"
        SLUG="${SLUG#$_t-}"
        break 2
      fi
    done
  done <<< "$VALID_BRANCH_TYPES"
  if [ -n "$DETECTED_TYPE" ]; then
    BRANCH="$DETECTED_TYPE/$SLUG"
  else
    BRANCH="feat/$SLUG"
  fi
fi

parse_branch "$BRANCH"
SLUG="$BRANCH_DESC"
BASE_BRANCH="${2:-main}"
PROJ="$(sanitize_proj "$BRANCH")"
WORKTREE="$(worktree_path_for_slug "$SLUG")"

log "Preparing isolated worktree for '$BRANCH' at $WORKTREE"

if git -C "$PRIMARY_ROOT" remote get-url origin >/dev/null 2>&1; then
  git -C "$PRIMARY_ROOT" fetch origin --quiet || warn "git fetch failed; using local $BASE_BRANCH"
  git -C "$PRIMARY_ROOT" rev-parse --verify "origin/$BASE_BRANCH" >/dev/null 2>&1 && BASE_REF="origin/$BASE_BRANCH" || BASE_REF="$BASE_BRANCH"
else
  BASE_REF="$BASE_BRANCH"
fi

if [ -d "$WORKTREE" ]; then
  warn "worktree already exists at $WORKTREE — reusing it"
else
  mkdir -p "$WORKTREE_PARENT"
  if git -C "$PRIMARY_ROOT" rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
    git -C "$PRIMARY_ROOT" worktree add "$WORKTREE" "$BRANCH"
  else
    git -C "$PRIMARY_ROOT" worktree add -b "$BRANCH" "$WORKTREE" "$BASE_REF"
  fi
  ok "worktree created at $WORKTREE (branch $BRANCH from $BASE_REF)"
fi

# --- Allocate ports under the registry lock ---------------------------------
registry_lock
trap registry_unlock EXIT

if [ -f "$REGISTRY_FILE" ] && grep -qP "^$BRANCH\t" "$REGISTRY_FILE" 2>/dev/null; then
  PG="$(registry_get "$BRANCH" 3)"; RD="$(registry_get "$BRANCH" 4)"
  API="$(registry_get "$BRANCH" 5)"; FE="$(registry_get "$BRANCH" 6)"
  ok "reusing registered ports pg=$PG redis=$RD api=$API fe=$FE"
else
  BASE="$(alloc_port_block "$BRANCH")"
  PG=$((BASE + 0)); RD=$((BASE + 1)); API=$((BASE + 2)); FE=$((BASE + 3))
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$BRANCH" "$PROJ" "$PG" "$RD" "$API" "$FE" "$WORKTREE" >> "$REGISTRY_FILE"
  ok "allocated ports pg=$PG redis=$RD api=$API fe=$FE"
fi
registry_unlock
trap - EXIT

cat > "$WORKTREE/.env.local" <<EOF
# Auto-generated by setup-worktree.sh — do NOT commit, do NOT hand-edit ports.
COMPOSE_PROJECT_NAME=$PROJ
POSTGRES_PORT=$PG
REDIS_PORT=$RD
API_PORT=$API
FRONTEND_PORT=$FE
EOF
ok ".env.local written"

# Best-effort: copy local Cursor harness so agents keep project skills/rules.
if [ -d "$PRIMARY_ROOT/.cursor" ] && [ ! -e "$WORKTREE/.cursor" ]; then
  cp -a "$PRIMARY_ROOT/.cursor" "$WORKTREE/.cursor" 2>/dev/null \
    && ok "copied .cursor/ harness into worktree" \
    || warn "could not copy .cursor/ (optional)"
fi

# Sync agent scripts from primary so parallel trees get latest harness even when
# the worktree was branched from an older main.
if [ -d "$PRIMARY_ROOT/scripts/agent" ]; then
  mkdir -p "$WORKTREE/scripts/agent"
  cp -a "$PRIMARY_ROOT/scripts/agent/." "$WORKTREE/scripts/agent/" 2>/dev/null \
    && ok "synced scripts/agent/ from primary" \
    || warn "could not sync scripts/agent/ (optional)"
fi

echo ""
echo "  MODE=parallel"
echo "  BRANCH=$BRANCH"
echo "  Workspace ready. Next steps:"
echo "    1. move_agent_to_root → $WORKTREE   (or: cd \"$WORKTREE\")"
echo "    2. bash scripts/agent/run-services.sh"
echo ""
# Last line = worktree path (machine-readable for the caller).
echo "$WORKTREE"
