#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# setup-worktree.sh <branch> [base-branch]
#
# Creates an isolated git worktree + branch for one feature, allocates a
# unique, race-free block of host ports, and writes the worktree's .env.local.
#
# <branch> follows the Conventional Branch v1.1.0 spec:
#   <type>/<description>          — e.g. feature/eng-123-add-login
#   <slug>                       — shorthand, defaults to feature/<slug>
#
# Valid types: feature, feat, bugfix, fix, hotfix, release, chore, ai,
#              copilot, cursor, claude, codex
#
# Prints the worktree path on the LAST line so the caller can `cd` into it.
# ---------------------------------------------------------------------------
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$HERE/lib.sh"

[ $# -ge 1 ] || die "usage: setup-worktree.sh <branch|slug> [base-branch]"

# Accept either "feature/eng-123-add-login" or plain "add-login" (defaults to feature/).
INPUT="$1"
if echo "$INPUT" | grep -q '/'; then
  # Full conventional branch name — validate it.
  BRANCH="$INPUT"
  validate_conventional_branch "$BRANCH" || die "branch '$BRANCH' violates Conventional Branch v1.1.0"
else
  # Plain slug — default to feature/ unless it starts with a known type prefix.
  SLUG="$(sanitize_proj "$INPUT")"
  [ -n "$SLUG" ] || die "empty/invalid feature slug"
  # Check if the slug starts with a recognized branch type (e.g. "fix-" → fix/)
  DETECTED_TYPE=""
  while IFS='|' read -ra _types; do
    for _t in "${_types[@]}"; do
      if [[ "$SLUG" == "$_t-"* ]]; then
        DETECTED_TYPE="$_t"
        SLUG="${SLUG#$_t-}"
        break 2
      fi
    done
  done <<< "$VALID_BRANCH_TYPES"
  if [ -n "$DETECTED_TYPE" ]; then
    BRANCH="$DETECTED_TYPE/$SLUG"
  else
    BRANCH="feature/$SLUG"
  fi
fi

parse_branch "$BRANCH"
SLUG="$BRANCH_DESC"   # worktree directory and docker project use the description part.
BASE_BRANCH="${2:-main}"
PROJ="$(sanitize_proj "$BRANCH")"
WORKTREE="$REGISTRY_DIR/$SLUG"

log "Preparing isolated workspace for '$BRANCH'"

# Always branch from the freshest base so agents start from current main.
if git remote get-url origin >/dev/null 2>&1; then
  git -C "$PRIMARY_ROOT" fetch origin --quiet || warn "git fetch failed; using local $BASE_BRANCH"
  git rev-parse --verify "origin/$BASE_BRANCH" >/dev/null 2>&1 && BASE_REF="origin/$BASE_BRANCH" || BASE_REF="$BASE_BRANCH"
else
  BASE_REF="$BASE_BRANCH"
fi

if [ -d "$WORKTREE" ]; then
  warn "worktree already exists at $WORKTREE — reusing it"
else
  if git -C "$PRIMARY_ROOT" rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
    git -C "$PRIMARY_ROOT" worktree add "$WORKTREE" "$BRANCH"
  else
    git -C "$PRIMARY_ROOT" worktree add -b "$BRANCH" "$WORKTREE" "$BASE_REF"
  fi
  ok "worktree created at $WORKTREE (branch $BRANCH from $BASE_REF)"
fi

# --- Allocate ports under the registry lock (atomic across parallel setups) --
registry_lock
trap registry_unlock EXIT

if [ -f "$REGISTRY_FILE" ] && grep -qP "^$BRANCH\t" "$REGISTRY_FILE" 2>/dev/null; then
  PG="$(registry_get "$BRANCH" 3)"; RD="$(registry_get "$BRANCH" 4)"
  API="$(registry_get "$BRANCH" 5)"; FE="$(registry_get "$BRANCH" 6)"
  ok "reusing registered ports pg=$PG redis=$RD api=$API fe=$FE"
else
  BASE="$(alloc_port_block "$BRANCH")"
  PG=$((BASE + 0)); RD=$((BASE + 1)); API=$((BASE + 2)); FE=$((BASE + 3))
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$BRANCH" "$PROJ" "$PG" "$RD" "$API" "$FE" >> "$REGISTRY_FILE"
  ok "allocated ports pg=$PG redis=$RD api=$API fe=$FE"
fi
registry_unlock
trap - EXIT

# --- Write the per-worktree .env.local --------------------------------------
cat > "$WORKTREE/.env.local" <<EOF
# Auto-generated by setup-worktree.sh — do NOT commit, do NOT hand-edit ports.
COMPOSE_PROJECT_NAME=$PROJ
POSTGRES_PORT=$PG
REDIS_PORT=$RD
API_PORT=$API
FRONTEND_PORT=$FE
EOF
ok ".env.local written"

echo ""
echo "  Workspace ready. Next steps (run from inside the worktree):"
echo "    cd \"$WORKTREE\""
echo "    bash scripts/agent/run-services.sh"
echo ""
# Last line = worktree path (machine-readable for the caller).
echo "$WORKTREE"
